title: Scratch 3.0 phrasebook
hero_image: images/banner.png
description: Translate useful phrases into different languages with an interactive phrasebook
version: 4
listed: false
copyedit: true
ingredient: false
last_tested: "2018-12-03"
steps:
  - title: Introduction
  - title: "Scratch 3.0's new look"
  - title: Draw sprites and a backdrop
  - title: Google Translate
  - title: Switch the backdrop
  - title: Text to Speech
  - title: More phrases
  - title: "Challenge: how much does it cost?"
    challenge: true 
  - title: More languages
  - title: "Challenge: use Scratch 3.0 extensions in other projects"
    challenge: true
