title: scratch-3-phrasebook
hero_image: images/banner.png
description: scratch-3-phrasebook description
version: 4
listed: false
copyedit: false
last_tested: "2018-12-03"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
